Simplify update script and IGNORE handling
Dropped the notion of profiles; it doesn't really matter if some extra files
are linked on every machine. Dropped support for per-dir Makefiles, since I
wasn't using them anymore and it's cumberson. Dropped support for DOTFILES in
favor of just linking everything.

IGNORE is now a simple list of strings suitable for input to fgrep; anything
matched will not be complained about as an extra file. This makes it easier to
ignore entire directory hierarchies without having to specify each individual
file.

diff --git a/update b/update
--- a/update
+++ b/update
@@ -4,14 +4,7 @@ warn() {
   echo "==> $*"
 }
 
-# If PROFILES exists and there is a line that matches the hostname, use that
-# line as a space-delimited list of profiles (directories).  Otherwise, simply
-# use the default and hostname profiles.
-host=$(hostname)
-host=${host%%.*}
-profiles=$(grep "^$host " PROFILES 2>/dev/null)
-test -n "$profiles" || profiles="$host default"
-
+# Create and clean up temporary files.
 trap 'rm $tmp $expected' EXIT
 tmp=$(mktemp /tmp/etcupdate.XXXXXXX) || exit 1
 expected=$(mktemp /tmp/etcupdate.XXXXXXX) || exit 1
@@ -26,50 +19,41 @@ while getopts fqv opt; do
   esac
 done
 
-for profile in $profiles; do
-  test -d "$profile" || continue
-  # If Makefile exists, use it.
-  test -e "$profile/Makefile" && (cd "$profile" && make)
+# Find all non-directory files whose names (and parent directories' names)
+# don't begin with a dot. Use sed to strip the leading "./". Assumes no spaces
+# in filenames.
+files=$(find . -name '.[^.]*' -prune -o -not -type d -print | sed -e 's}^\./}}')
+for file in $files; do
+  test $file = IGNORE -o $file = $(basename $0) && continue
+  target="$HOME/.$file"
+  echo $target >>"$expected"
 
-  # If DOTFILES exists, it is a list of files to be copied to the destination.
-  # By default, all files are copied.
-  files=$(cat "$profile/DOTFILES" 2>/dev/null)
-  if [ -z "$files" ]; then
-    files=$(find "$profile" -maxdepth 1 -type f | sed -e 's}.*/}}')
+  # Ensure the target directory exists.
+  targetd=$(dirname $target)
+  test -d $targetd || mkdir -p $targetd
+
+  # If the target exists and is correctly linked, go on to the next file. If it
+  # exists but doesn't match the source file and -f was not given, display a
+  # warning (and the diff, if -v was given) and go on to the next file.
+  if [ -e $target ]; then
+    test $target -ef $file && continue
+    if [ -z "$force" ] && ! cmp -s $file $target; then
+      warn ".$file is stale"
+      test -n "$verbose" && diff -u $target $file
+      continue
+    fi
   fi
 
-  # If IGNORE exists, do not warn about extra files listed there.
-  sed -e "s}^}$HOME/.}" -e 'y},}/}' "$profile/IGNORE" >>$expected 2>/dev/null
-
-  for file in $files; do
-    target="$HOME/.$(echo $file | tr , /)"
-    targetd=$(dirname "$target")
-    test "$file" = "IGNORE" && continue
-    echo $target >>$expected
-    source="$profile/$file"
-
-    if [ -e "$target" -o -L "$target" ]; then
-      test "$source" -ef "$target" && continue
-
-      cmp -s "$source" "$target"; differ=$?
-      if [ $differ -eq 1 -a -z "$force" ]; then
-        warn "$target is stale"
-        test -n "$verbose" && diff -u "$target" "$source"
-        continue
-      fi
-    fi
-
-    test -d "$targetd" || mkdir -p "$targetd"
-    ln -fv "$profile/$file" "$target"
-  done
+  # Create the link.
+  ln -fv $file $target
 done
 
 # Check for extra files in $HOME and display them.
 if [ -z "$quiet" ]; then
-  sort $expected >$tmp && cp $tmp $expected
-  find "$HOME"/.[^.]* ! -type d | sort >$tmp
-  if ! cmp -s $tmp $expected; then
-    warn "Extra files in $HOME:"
-    comm -23 $tmp $expected
+  sort "$expected" >"$tmp" && cp "$tmp" "$expected"
+  find "$HOME"/.[^.]* -not -type d | fgrep -vf IGNORE | sort >"$tmp"
+  if ! cmp -s "$tmp" "$expected"; then
+    warn 'Extra files:'
+    comm -23 "$tmp" "$expected"
   fi
 fi
